import type { ImportParserKind } from "@/shared/types/imports";
import type { ImportTemplate } from "@/shared/types/import-templates";

function aliases(...values: string[]) {
  return values;
}

export const systemImportTemplates: ImportTemplate[] = [
  {
    id: "generic-cl",
    workspaceId: null,
    name: "Generico Chile",
    institution: "Generico",
    parser: "csv",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 1,
    filenameHints: [],
    headerHints: aliases("fecha", "descripcion", "glosa", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha", "fecha movimiento", "fecha transaccion"),
      description: aliases("descripcion", "descripción", "glosa", "detalle", "concepto"),
      amount: aliases("monto", "importe", "total"),
      debit: aliases("cargo", "debito", "débito"),
      credit: aliases("abono", "credito", "crédito"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto", "tarjeta"),
      type: aliases("tipo", "tipo movimiento")
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy", "dd-MM-yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "generic-cl-xlsx",
    workspaceId: null,
    name: "Generico Chile Excel",
    institution: "Generico",
    parser: "xlsx",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 1,
    filenameHints: [],
    headerHints: aliases("fecha", "descripcion", "glosa", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha", "fecha movimiento", "fecha transaccion"),
      description: aliases("descripcion", "descripción", "glosa", "detalle", "concepto"),
      amount: aliases("monto", "importe", "total"),
      debit: aliases("cargo", "debito", "débito"),
      credit: aliases("abono", "credito", "crédito"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto", "tarjeta"),
      type: aliases("tipo", "tipo movimiento")
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy", "dd-MM-yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "generic-cl-pdf",
    workspaceId: null,
    name: "Generico Chile PDF",
    institution: "Generico",
    parser: "pdf",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 1,
    filenameHints: [],
    headerHints: aliases("fecha", "descripcion", "glosa", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "glosa", "detalle", "concepto"),
      amount: aliases("monto", "importe"),
      debit: aliases("cargo", "debito", "débito"),
      credit: aliases("abono", "credito", "crédito"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto", "tarjeta"),
      type: aliases("tipo")
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy", "dd-MM-yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "banco-chile-cartola",
    workspaceId: null,
    name: "Banco de Chile Cartola",
    institution: "Banco de Chile",
    parser: "xlsx",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 100,
    filenameHints: aliases("banco de chile", "chile"),
    headerHints: aliases("fecha", "descripcion", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha", "fecha movimiento"),
      description: aliases("descripcion", "descripción", "detalle"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  },
  {
    id: "banco-chile-cartola-pdf",
    workspaceId: null,
    name: "Banco de Chile Cartola PDF",
    institution: "Banco de Chile",
    parser: "pdf",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 100,
    filenameHints: aliases("banco de chile", "chile"),
    headerHints: aliases("fecha", "descripcion", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "descripción", "detalle"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  },
  {
    id: "bci-cartola",
    workspaceId: null,
    name: "BCI Movimientos",
    institution: "BCI",
    parser: "xlsx",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 96,
    filenameHints: aliases("bci"),
    headerHints: aliases("fecha", "detalle", "monto", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("detalle", "descripcion", "glosa"),
      amount: aliases("monto"),
      debit: [],
      credit: [],
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta"),
      type: aliases("tipo")
    },
    amountMode: "SIGNED",
    dateFormats: ["dd/MM/yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "bancoestado-cartola",
    workspaceId: null,
    name: "BancoEstado Cartola",
    institution: "BancoEstado",
    parser: "xlsx",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 95,
    filenameHints: aliases("bancoestado", "estado"),
    headerHints: aliases("fecha", "descripcion", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "descripción", "glosa"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta rut", "cuenta"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  },
  {
    id: "bancoestado-cartola-pdf",
    workspaceId: null,
    name: "BancoEstado Cartola PDF",
    institution: "BancoEstado",
    parser: "pdf",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 95,
    filenameHints: aliases("bancoestado", "estado"),
    headerHints: aliases("fecha", "descripcion", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "descripción", "glosa"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta rut", "cuenta"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  },
  {
    id: "santander-chile-cartola",
    workspaceId: null,
    name: "Santander Chile Movimientos",
    institution: "Santander Chile",
    parser: "csv",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 94,
    filenameHints: aliases("santander"),
    headerHints: aliases("fecha", "concepto", "importe", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("concepto", "detalle", "descripcion"),
      amount: aliases("importe", "monto"),
      debit: [],
      credit: [],
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto"),
      type: aliases("tipo movimiento")
    },
    amountMode: "SIGNED",
    dateFormats: ["dd/MM/yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "santander-chile-cartola-pdf",
    workspaceId: null,
    name: "Santander Chile PDF",
    institution: "Santander Chile",
    parser: "pdf",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 94,
    filenameHints: aliases("santander"),
    headerHints: aliases("fecha", "concepto", "importe", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("concepto", "detalle", "descripcion"),
      amount: aliases("importe", "monto"),
      debit: [],
      credit: [],
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta", "producto"),
      type: aliases("tipo movimiento")
    },
    amountMode: "SIGNED",
    dateFormats: ["dd/MM/yyyy", "yyyy-MM-dd"],
    hasBalance: true
  },
  {
    id: "falabella-cmr-cartola",
    workspaceId: null,
    name: "Banco Falabella / CMR",
    institution: "Banco Falabella",
    parser: "xlsx",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 93,
    filenameHints: aliases("falabella", "cmr"),
    headerHints: aliases("fecha", "glosa", "cargo", "abono"),
    columns: {
      date: aliases("fecha", "fecha transaccion"),
      description: aliases("glosa", "descripcion", "descripción"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("tarjeta", "cuenta"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  },
  {
    id: "scotiabank-chile-cartola",
    workspaceId: null,
    name: "Scotiabank Chile",
    institution: "Scotiabank",
    parser: "csv",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 92,
    filenameHints: aliases("scotiabank", "scotia"),
    headerHints: aliases("fecha", "descripcion", "monto", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "descripción", "detalle"),
      amount: aliases("monto"),
      debit: [],
      credit: [],
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta"),
      type: aliases("tipo")
    },
    amountMode: "SIGNED",
    dateFormats: ["dd/MM/yyyy", "dd-MM-yyyy"],
    hasBalance: true
  },
  {
    id: "itau-chile-cartola",
    workspaceId: null,
    name: "Itau Chile Movimientos",
    institution: "Itau",
    parser: "csv",
    sourceType: "system",
    isSystem: true,
    isActive: true,
    detectionPriority: 91,
    filenameHints: aliases("itau"),
    headerHints: aliases("fecha", "descripcion", "cargo", "abono", "saldo"),
    columns: {
      date: aliases("fecha"),
      description: aliases("descripcion", "descripción", "glosa"),
      amount: [],
      debit: aliases("cargo"),
      credit: aliases("abono"),
      balance: aliases("saldo"),
      sourceAccountName: aliases("cuenta"),
      type: []
    },
    amountMode: "SEPARATE_DEBIT_CREDIT",
    dateFormats: ["dd/MM/yyyy"],
    hasBalance: true
  }
];

export function listSystemImportTemplates(parser?: ImportParserKind) {
  const templates = parser
    ? systemImportTemplates.filter((template) => template.parser === parser)
    : systemImportTemplates;
  return templates.sort((left, right) => right.detectionPriority - left.detectionPriority);
}
